#!/usr/bin/env bash
# pipeline_04_build_bible_md.sh
#
# Takes the raw pdftotext extraction (bible-pdftotext.md, produced by
# pipeline_01_pdftotext.sh) and structurally parses it into the final,
# clean bible.md: book headers with anchors, a linked table of contents,
# "### Chapter N" headings, and bold (**N**) verse numbers.
#
# NOTE: this is a best-effort reconstruction of the parsing step. The
# exact original heuristics used to build bible.md aren't recoverable
# from this conversation (bible.md arrived pre-built), so review the
# output against your original and adjust the regexes below as needed.
#
# Usage:
#   ./pipeline_04_build_bible_md.sh [path/to/bible-pdftotext.md] [output_dir]

set -euo pipefail

IN_FILE="${1:-bible-pdftotext.md}"
OUT_DIR="${2:-.}"
OUT_FILE="${OUT_DIR}/bible.md"

mkdir -p "${OUT_DIR}"

if [[ ! -f "${IN_FILE}" ]]; then
  echo "Error: ${IN_FILE} not found. Run pipeline_01_pdftotext.sh first." >&2
  exit 1
fi

echo "Parsing ${IN_FILE} -> ${OUT_FILE}..."

python3 - "${IN_FILE}" "${OUT_FILE}" <<'PYEOF'
import re
import sys

in_path, out_path = sys.argv[1], sys.argv[2]

# Canonical NT book order: (Mapudungun name, English gloss, anchor slug)
BOOKS = [
    ("Matew", "Matthew", "matew"),
    ("Marku", "Mark", "marku"),
    ("Luka", "Luke", "luka"),
    ("Juan", "John", "juan"),
    ("Hecho", "Acts", "hecho"),
    ("Romanu", "Romans", "romanu"),
    ("1 Korintio", "1 Corinthians", "1-korintio"),
    ("2 Korintio", "2 Corinthians", "2-korintio"),
    ("Galata", "Galatians", "galata"),
    ("Efesio", "Ephesians", "efesio"),
    ("Filipense", "Philippians", "filipense"),
    ("Kolosense", "Colossians", "kolosense"),
    ("1 Tesalonisense", "1 Thessalonians", "1-tesalonisense"),
    ("2 Tesalonisense", "2 Thessalonians", "2-tesalonisense"),
    ("1 Timotew", "1 Timothy", "1-timotew"),
    ("2 Timotew", "2 Timothy", "2-timotew"),
    ("Tito", "Titus", "tito"),
    ("Filemon", "Philemon", "filemon"),
    ("Ebrew", "Hebrews", "ebrew"),
    ("Santiaw", "James", "santiaw"),
    ("1 Pedro", "1 Peter", "1-pedro"),
    ("2 Pedro", "2 Peter", "2-pedro"),
    ("1 Juan", "1 John", "1-juan"),
    ("2 Juan", "2 John", "2-juan"),
    ("3 Juan", "3 John", "3-juan"),
    ("Juda", "Jude", "juda"),
    ("Apokalipsi", "Revelation", "apokalipsi"),
]

def read_text(path):
    with open(path, "rb") as f:
        data = f.read()
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        # Fallback for input generated by a pdftotext run without
        # -enc UTF-8 (older bible-pdftotext.md files, Latin-1-ish output)
        print("WARNING: input is not valid UTF-8, decoding as Latin-1 "
              "(cp1252). Re-run pipeline_01 with -enc UTF-8 to avoid this.",
              file=sys.stderr)
        return data.decode("cp1252", errors="replace")

raw = read_text(in_path)

# Strip the ```text fence wrapper added by pipeline_01_pdftotext.sh, if present
m = re.search(r"```text\n(.*)\n```", raw, flags=re.DOTALL)
if m:
    raw = m.group(1)

# Drop the page-break markers pdftotext left in ("--- page N ---" from other
# extractors won't be present here, but pdftotext itself uses form-feed \x0c)
raw = raw.replace("\x0c", "\n")

# 1. Split the raw text into per-book chunks using the known book names as
#    anchors. Book title lines are matched as a standalone line (possibly
#    with leading/trailing whitespace) equal to the Mapudungun book name.
book_positions = []
for name, gloss, slug in BOOKS:
    pattern = re.compile(rf"^\s*{re.escape(name)}\s*$", re.MULTILINE)
    match = pattern.search(raw)
    if match:
        book_positions.append((match.start(), name, gloss, slug))
    else:
        print(f"WARNING: could not locate book heading for '{name}' — "
              f"check spelling/casing in the raw extraction.", file=sys.stderr)

book_positions.sort()

chunks = []
for i, (pos, name, gloss, slug) in enumerate(book_positions):
    end = book_positions[i + 1][0] if i + 1 < len(book_positions) else len(raw)
    chunks.append((name, gloss, slug, raw[pos:end]))

# 2. Within each chunk: mark chapter breaks and bold verse numbers.
CHAPTER_RE = re.compile(r"^\s*(?:Chapter|Capitulo)\s+(\d+)\s*$", re.IGNORECASE | re.MULTILINE)
# A verse number: an integer alone at the start of a line, followed by text.
VERSE_RE = re.compile(r"^(\d{1,3})\s+(?=\S)", re.MULTILINE)

def format_chunk(name, body):
    # Remove the leading book-name line itself (already used as the heading)
    body = re.sub(rf"^\s*{re.escape(name)}\s*\n", "", body, count=1)
    body = CHAPTER_RE.sub(lambda m: f"### Chapter {m.group(1)}", body)
    body = VERSE_RE.sub(lambda m: f"**{m.group(1)}** ", body)
    return body.strip()

# 3. Assemble the final document: copyright header, TOC, then each book.
header = """# Ng\u00fcnechen \u00d1i K\u00fcme Dungu
### New Testament in Mapudungun (arn)

> **Copyright \u00a9 2011, Wycliffe Bible Translators, Inc. All rights reserved.**
> Licensed under Creative Commons Attribution\u2013NonCommercial\u2013NoDerivatives.
> You may share, copy, distribute, transmit, and port this text to other file
> formats, provided you (1) retain this attribution, (2) do not sell it, and
> (3) do not alter any of the words or punctuation.
> Source: https://ebible.org/pdf/arnNT/arnNT_prt.pdf

---

**Extraction note:** Full text extracted from the official Wycliffe Bible
Translators PDF using `pdftotext -layout` (poppler-utils), then structurally
parsed into Markdown (book/chapter headers, bolded verse numbers) via
pipeline_04_build_bible_md.sh. All books present in the source PDF are
included, unaltered in wording.

---

## Contents

"""

toc_lines = [f"- [{name} ({gloss})](#{slug})" for name, gloss, slug, _ in chunks]
toc = "\n".join(toc_lines) + "\n\n---\n\n"

book_sections = []
for name, gloss, slug, body in chunks:
    formatted = format_chunk(name, body)
    book_sections.append(
        f'## {name} <a id="{slug}"></a>\n*({gloss})*\n\n{formatted}\n'
    )

output = header + toc + "\n".join(book_sections)

with open(out_path, "w", encoding="utf-8") as f:
    f.write(output)

print(f"Parsed {len(chunks)} of {len(BOOKS)} books.")
PYEOF

echo "Done -> ${OUT_FILE}"
echo "Review the output against your reference bible.md and adjust the"
echo "CHAPTER_RE / VERSE_RE patterns in this script if formatting differs."
